# Generated by Django 4.0.4 on 2022-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('start_time', models.TimeField(verbose_name='Время подачи автомобиля')),
                ('end_time', models.TimeField(verbose_name='Время окончания выполнения заказа')),
                ('contact_person', models.CharField(max_length=128, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Телефон контактного лица')),
                ('is_employee', models.BooleanField(verbose_name="Является сотрудником ГК 'Деловые линиии'")),
                ('address_point_A', models.CharField(max_length=255, verbose_name='Адрес пункта отправления')),
                ('address_point_B', models.CharField(max_length=255, verbose_name='Адрес пункта прибытия')),
                ('pos_x_A', models.FloatField(verbose_name="Координата 'Х' пункта отправления")),
                ('pos_x_B', models.FloatField(verbose_name="Координата 'Х' пункта прибытия")),
                ('pos_y_A', models.FloatField(verbose_name="Координата 'Y' пункта отправления")),
                ('pos_y_B', models.FloatField(verbose_name="Координата 'Y' пункта прибытия")),
                ('comments', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарии к заказу')),
                ('cargo_type', models.CharField(choices=[('cargo', 'Груз'), ('passenger', 'Пассажир'), ('docs', 'Документы')], max_length=16, verbose_name='Тип груза')),
                ('power_attorney', models.BooleanField(verbose_name='Наличие доверенности')),
                ('stamp', models.BooleanField(verbose_name='Наличие печати')),
                ('stamp_company', models.CharField(blank=True, choices=[('Company_1', 'Компания Раз'), ('Company_2', 'Компания Два')], max_length=64, null=True, verbose_name='Печать компании')),
                ('cargo_size', models.CharField(blank=True, max_length=32, null=True, verbose_name='Габариты груза')),
                ('cargo_volume', models.FloatField(blank=True, null=True, verbose_name='Объем груза')),
                ('cargo_weight', models.FloatField(blank=True, null=True, verbose_name='Вес груза')),
                ('passenger_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='ФИО пассажира')),
                ('passenger_phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон пассажира')),
                ('order_record_date', models.DateField(auto_now_add=True, verbose_name='Дата оформления заказа')),
            ],
        ),
    ]
